version: "1"

services:   
  mongo:
    image: mongo:latest
    container_name: db-mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=qwer1234
    ports:
    - 27019:27017
    networks:
    - tdparcial2025
    
networks:
  tdparcial2025:
    name: msparcial

